Repository BinaryAnalysisPlatform/bap, pull requests merged in 2020-07, with the labels that each got.

#1164 splits oasis multipackages into sub-packages
  configure-omake
  oasis/elf-loader
  oasis/emit-ida-script
  oasis/legacy-llvm
  oasis/llvm
  oasis/piqi-printers
  oasis/piqi-printers.ocamlbuild.ml.in
  oasis/piqi-printers.setup.ml.in
  oasis/primus-exploring
  oasis/primus-greedy
  oasis/primus-limit
  oasis/primus-loader
  oasis/primus-mark-visited
  oasis/primus-print
  oasis/primus-promiscuous
  oasis/primus-propagate-taint
  oasis/primus-round-robin
  oasis/primus-support
  oasis/primus-taint
  oasis/primus-taint.setup.ml.in
  oasis/primus-track-visited
  oasis/primus-wandering
  oasis/read-symbols
  oasis/taint
Labels: urgent

#1171 creates a separate package for the strings plugin
  oasis/beagle
  oasis/strings
  oasis/strings_library
Labels: ready for review

#1139 Add Docker Publish Action
  .github/workflows/publish-docker-image.yml
  docker/ubuntu/xenial/Dockerfile
Labels: ready for review

#1191 fixes build on Debian-testing
  docker/debian/testing/Dockerfile
Labels: CI
